### ISSUE TITLE
[Enhancement]: Allow saving cities

### ISSUE THREAD

**Issue by sago007** [diddledan/micropolis-snap#1]
### What changes would you like?

It should be possible to save cities.

At the moment the default folder for storing cities is write protected and there is no easy way to find a writeable folder.

This renders the game practically unplayable.

It does not look like the upstream game is optimized for multiuser systems.

Possible solutions could be:
1. Make the "cities" folder a layered filesystem, so that you can write to it. (I do not know if snap supports it)
2. Add a "writeable" folder in "cities" that maps to a writeable folder.

**Comment by sago007** [comment]
I tested it. I get some weird feedback while trying to save (Ubuntu 20.04):
```
can't read "env(SNAP_USER_COMMON)": no such variable
    while executing
"set CityDir $env(SNAP_USER_COMMON)..."
    (procedure "UIDoReallySaveCity" line 6)
    invoked from within
"UIDoReallySaveCity [.file7.file.file get] [.file7.path.path get]"
    invoked from within
".file7.frame1.ok invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    ("then" clause line 2)
    invoked from within
"if {($w == $tk_priv(window@$screen))
	    && ([lindex [$w config -state] 4] != "disabled")} {
	uplevel #0 [list $w invoke]
    }"
    (procedure "tk_butUp" line 6)
    invoked from within
"tk_butUp .file7.frame1.ok"
    (command bound to event)
can't read "env(SNAP_USER_COMMON)": no such variable
    while executing
"set CityDir $env(SNAP_USER_COMMON)..."
    (procedure "UIDoReallySaveCity" line 6)
    invoked from within
"UIDoReallySaveCity [.file7.file.file get] [.file7.path.path get]"
    invoked from within
".file7.frame1.ok invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    ("then" clause line 2)
    invoked from within
"if {($w == $tk_priv(window@$screen))
	    && ([lindex [$w config -state] 4] != "disabled")} {
	uplevel #0 [list $w invoke]
    }"
    (procedure "tk_butUp" line 6)
    invoked from within
"tk_butUp .file7.frame1.ok"
    (command bound to event)
```

**Comment by ken-wawa-wawa** [comment]
I tried to save cities on Ubuntu 22.04.5LTS using Micropolis downloaded from "Ubuntu Software". Unfortunately saving doesn't work. Nothing happens. There is no error message, nothing. Just file is not being created and save dialog is not being closed. Upss....
